version: "3.8"

services:
  mysql:
    image: mysql:8.0.25
    container_name: wooahan-mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Wooahan11!
      MYSQL_DATABASE: wooahan
      TZ: Asia/Seoul

  redis:
    image: redis
    container_name: wooahan-redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./.resource/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.resource/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
