const questionListMock = [
  {
    id: 1,
    content: "하루에 물을 얼마나 마셔야 하나요?",
    status: "answered_by_expert",
    createdAt: "2024-10-28T10:00:00Z",
    answers: 5,
    creator: "활기찬고양이",
  },
  {
    id: 2,
    content: "건강에 좋은 아침 운동은 무엇인가요?",
    status: "answered_by_llm",
    createdAt: "2024-10-28T11:30:00Z",
    answers: 3,
    creator: "평온한여우",
  },
  {
    id: 3,
    content: "비타민 D는 어떻게 보충하나요?",
    status: "pending",
    createdAt: "2024-10-28T12:15:00Z",
    answers: 0,
    creator: "졸린부엉이",
  },
  {
    id: 4,
    content: "유산소 운동은 언제 하는 게 좋나요?",
    status: "answered_by_llm",
    createdAt: "2024-10-28T13:45:00Z",
    answers: 2,
    creator: "활동적인토끼",
  },
  {
    id: 5,
    content: "스트레스를 줄이는 방법이 있나요?",
    status: "answered_by_expert",
    createdAt: "2024-10-28T14:00:00Z",
    answers: 8,
    creator: "차분한판다",
  },
  {
    id: 6,
    content: "피부에 좋은 식품은 무엇인가요?",
    status: "answered_by_llm",
    createdAt: "2024-10-28T15:30:00Z",
    answers: 4,
    creator: "상큼한원숭이",
  },
  {
    id: 7,
    content: "매일 걷기의 건강 효과는 무엇인가요?",
    status: "answered_by_expert",
    createdAt: "2024-10-28T16:45:00Z",
    answers: 7,
    creator: "낙관적인돌고래",
  },
  {
    id: 8,
    content: "잠을 잘 자는 방법이 궁금해요.",
    status: "pending",
    createdAt: "2024-10-28T17:00:00Z",
    answers: 1,
    creator: "졸린부엉이",
  },
  {
    id: 9,
    content: "명상이 건강에 미치는 영향은 무엇인가요?",
    status: "answered_by_llm",
    createdAt: "2024-10-28T17:45:00Z",
    answers: 6,
    creator: "평온한여우",
  },
  {
    id: 10,
    content: "정기적인 건강 검진의 중요성은?",
    status: "answered_by_expert",
    createdAt: "2024-10-28T18:30:00Z",
    answers: 9,
    creator: "활기찬고양이",
  },
];

export default questionListMock;
